version: '3'

tasks:
  go:lint:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    cmds:
      - golangci-lint run -v

  go:test:
    desc: runs and outputs results of created go tests
    cmds:
      - go test -v ./...

  go:tidy:
    desc: runs go mod tidy
    aliases: [tidy]
    cmds:
      - go mod tidy

  go:all:
    aliases: [go]
    desc: runs all go test and lint related tasks
    cmds:
      - task: go:tidy
      - task: go:lint
      - task: go:test